<?php

namespace App\Utilities;

class Constant
{
    const USER_ROLE_SUPER_ADMIN = 'SUPER_ADMIN';
    const USER_ROLE_SUPER_ADMIN_BRANCH = 'SUPER_ADMIN_BRANCH';
    const USER_ROLE_ADMIN = 'ADMIN';
    const USER_ROLE_FINANCE = 'FINANCE';
    const USER_ROLE_SALES = 'SALES';
    const USER_ROLE_WAREHOUSE = 'WAREHOUSE';

    const USER_ROLES = [
        self::USER_ROLE_SUPER_ADMIN,
        self::USER_ROLE_SUPER_ADMIN_BRANCH,
        self::USER_ROLE_ADMIN,
        self::USER_ROLE_FINANCE,
        self::USER_ROLE_SALES,
        self::USER_ROLE_WAREHOUSE,
    ];
    const USER_ROLE_LABELS = [
        self::USER_ROLE_SUPER_ADMIN => 'Super Admin',
        self::USER_ROLE_SUPER_ADMIN_BRANCH => 'Super Admin Cabang',
        self::USER_ROLE_ADMIN => 'Admin',
        self::USER_ROLE_FINANCE => 'Finance',
        self::USER_ROLE_SALES => 'Sales',
        self::USER_ROLE_WAREHOUSE => 'Warehouse',
    ];

    const USER_STATUS_PENDING = 'PENDING';
    const USER_STATUS_ACTIVE = 'ACTIVE';
    const USER_STATUS_LABELS = [
        self::USER_STATUS_PENDING => 'Pending',
        self::USER_STATUS_ACTIVE => 'Aktif'
    ];

    const PRICE_TYPE_GENERAL = 'GENERAL';
    const PRICE_TYPE_RETAIL = 'RETAIL';
    const PRICE_TYPE_WHOLESALE = 'WHOLESALE';
    const PRICE_TYPES = [
        self::PRICE_TYPE_GENERAL,
        self::PRICE_TYPE_RETAIL,
        self::PRICE_TYPE_WHOLESALE,
    ];
    const PRICE_TYPE_LABELS = [
        self::PRICE_TYPE_GENERAL => 'Umum',
        self::PRICE_TYPE_RETAIL => 'Eceran',
        self::PRICE_TYPE_WHOLESALE => 'Grosir'
    ];

    const PLAN_ORDER_STATUS_ACTIVE = 'ACTIVE';
    const PLAN_ORDER_STATUS_UPDATED = 'UPDATED';
    const PLAN_ORDER_STATUS_CANCELLED = 'CANCELLED';
    const PLAN_ORDER_STATUS_LABELS = [
        self::PLAN_ORDER_STATUS_ACTIVE => 'Aktif',
        self::PLAN_ORDER_STATUS_UPDATED => 'Update',
        self::PLAN_ORDER_STATUS_CANCELLED => 'Batal',
    ];

    const GOODS_RECEIPT_STATUS_ACTIVE = 'ACTIVE';
    const GOODS_RECEIPT_STATUS_WAITING_APPROVAL = 'WAITING_APPROVAL';
    const GOODS_RECEIPT_STATUS_UPDATED = 'UPDATED';
    const GOODS_RECEIPT_STATUS_CANCELLED = 'CANCELLED';
    const GOODS_RECEIPT_STATUS_LABELS = [
        self::GOODS_RECEIPT_STATUS_ACTIVE => 'Aktif',
        self::GOODS_RECEIPT_STATUS_WAITING_APPROVAL => 'Menunggu Approval',
        self::GOODS_RECEIPT_STATUS_UPDATED => 'Update',
        self::GOODS_RECEIPT_STATUS_CANCELLED => 'Batal',
    ];

    const SALES_ORDER_STATUS_ACTIVE = 'ACTIVE';
    const SALES_ORDER_STATUS_WAITING_APPROVAL = 'WAITING_APPROVAL';
    const SALES_ORDER_STATUS_UPDATED = 'UPDATED';
    const SALES_ORDER_STATUS_CANCELLED = 'CANCELLED';
    const SALES_ORDER_STATUS_LABELS = [
        self::SALES_ORDER_STATUS_ACTIVE => 'Aktif',
        self::SALES_ORDER_STATUS_WAITING_APPROVAL => 'Menunggu Approval',
        self::SALES_ORDER_STATUS_UPDATED => 'Update',
        self::SALES_ORDER_STATUS_CANCELLED => 'Batal',
    ];

    const SALES_ORDER_DELIVERY_STATUS_ACTIVE = 'ACTIVE';
    const SALES_ORDER_DELIVERY_STATUS_ON_PROGRESS = 'ON_PROGRESS';
    const SALES_ORDER_DELIVERY_STATUS_COMPLETED = 'COMPLETED';
    const SALES_ORDER_DELIVERY_STATUS_LABELS = [
        self::SALES_ORDER_DELIVERY_STATUS_ACTIVE => 'Active',
        self::SALES_ORDER_DELIVERY_STATUS_ON_PROGRESS => 'On Progress',
        self::SALES_ORDER_DELIVERY_STATUS_COMPLETED => 'Completed',
    ];

    const SALES_ORDER_TYPE_RETAIL = 'RETAIL';
    const SALES_ORDER_TYPE_WHOLESALE = 'WHOLESALE';
    const SALES_ORDER_TYPE_LABELS = [
        self::SALES_ORDER_TYPE_RETAIL => 'Eceran',
        self::SALES_ORDER_TYPE_WHOLESALE => 'Grosir',
    ];

    const DELIVERY_ORDER_STATUS_ACTIVE = 'ACTIVE';
    const DELIVERY_ORDER_STATUS_WAITING_APPROVAL = 'WAITING_APPROVAL';
    const DELIVERY_ORDER_STATUS_UPDATED = 'UPDATED';
    const DELIVERY_ORDER_STATUS_CANCELLED = 'CANCELLED';
    const DELIVERY_ORDER_STATUS_LABELS = [
        self::DELIVERY_ORDER_STATUS_ACTIVE => 'Aktif',
        self::DELIVERY_ORDER_STATUS_WAITING_APPROVAL => 'Menunggu Approval',
        self::DELIVERY_ORDER_STATUS_UPDATED => 'Update',
        self::DELIVERY_ORDER_STATUS_CANCELLED => 'Batal',
    ];

    const SALES_RETURN_STATUS_ACTIVE = 'ACTIVE';
    const SALES_RETURN_STATUS_WAITING_APPROVAL = 'WAITING_APPROVAL';
    const SALES_RETURN_STATUS_UPDATED = 'UPDATED';
    const SALES_RETURN_STATUS_CANCELLED = 'CANCELLED';
    const SALES_RETURN_STATUS_LABELS = [
        self::SALES_RETURN_STATUS_ACTIVE => 'Aktif',
        self::SALES_RETURN_STATUS_WAITING_APPROVAL => 'Menunggu Approval',
        self::SALES_RETURN_STATUS_UPDATED => 'Update',
        self::SALES_RETURN_STATUS_CANCELLED => 'Batal',
    ];

    const SALES_RETURN_DELIVERY_STATUS_ACTIVE = 'ACTIVE';
    const SALES_RETURN_DELIVERY_STATUS_ONGOING = 'ONGOING';
    const SALES_RETURN_DELIVERY_STATUS_COMPLETED = 'COMPLETED';
    const SALES_RETURN_DELIVERY_STATUS_LABELS = [
        self::SALES_RETURN_DELIVERY_STATUS_ACTIVE => 'Aktif',
        self::SALES_RETURN_DELIVERY_STATUS_ONGOING => 'Proses',
        self::SALES_RETURN_DELIVERY_STATUS_COMPLETED => 'Selesai',
    ];

    const SALES_RETURN_STATUSES = [
        self::SALES_RETURN_STATUS_ACTIVE,
        self::SALES_RETURN_STATUS_WAITING_APPROVAL,
        self::SALES_RETURN_STATUS_UPDATED,
        self::SALES_RETURN_STATUS_CANCELLED
    ];

    const SALES_RETURN_DELIVERY_STATUSES = [
        self::SALES_RETURN_DELIVERY_STATUS_ACTIVE,
        self::SALES_RETURN_DELIVERY_STATUS_ONGOING,
        self::SALES_RETURN_DELIVERY_STATUS_COMPLETED
    ];

    const PURCHASE_RETURN_STATUS_ACTIVE = 'ACTIVE';
    const PURCHASE_RETURN_STATUS_WAITING_APPROVAL = 'WAITING_APPROVAL';
    const PURCHASE_RETURN_STATUS_UPDATED = 'UPDATED';
    const PURCHASE_RETURN_STATUS_CANCELLED = 'CANCELLED';
    const PURCHASE_RETURN_STATUS_LABELS = [
        self::PURCHASE_RETURN_STATUS_ACTIVE => 'Aktif',
        self::PURCHASE_RETURN_STATUS_WAITING_APPROVAL => 'Menunggu Approval',
        self::PURCHASE_RETURN_STATUS_UPDATED => 'Update',
        self::PURCHASE_RETURN_STATUS_CANCELLED => 'Batal',
    ];

    const PURCHASE_RETURN_RECEIPT_STATUS_ACTIVE = 'ACTIVE';
    const PURCHASE_RETURN_RECEIPT_STATUS_ONGOING = 'ONGOING';
    const PURCHASE_RETURN_RECEIPT_STATUS_COMPLETED = 'COMPLETED';
    const PURCHASE_RETURN_RECEIPT_STATUS_LABELS = [
        self::PURCHASE_RETURN_RECEIPT_STATUS_ACTIVE => 'Aktif',
        self::PURCHASE_RETURN_RECEIPT_STATUS_ONGOING => 'Proses',
        self::PURCHASE_RETURN_RECEIPT_STATUS_COMPLETED => 'Selesai',
    ];

    const PURCHASE_RETURN_STATUSES = [
        self::PURCHASE_RETURN_STATUS_ACTIVE,
        self::PURCHASE_RETURN_STATUS_WAITING_APPROVAL,
        self::PURCHASE_RETURN_STATUS_UPDATED,
        self::PURCHASE_RETURN_STATUS_CANCELLED
    ];

    const PURCHASE_RETURN_RECEIPT_STATUSES = [
        self::PURCHASE_RETURN_RECEIPT_STATUS_ACTIVE,
        self::PURCHASE_RETURN_RECEIPT_STATUS_ONGOING,
        self::PURCHASE_RETURN_RECEIPT_STATUS_COMPLETED
    ];

    const ACCOUNT_PAYABLE_STATUS_UNPAID = 'UNPAID';
    const ACCOUNT_PAYABLE_STATUS_ONGOING = 'ONGOING';
    const ACCOUNT_PAYABLE_STATUS_PAID = 'PAID';
    const ACCOUNT_PAYABLE_STATUS_LABELS = [
        self::ACCOUNT_PAYABLE_STATUS_UNPAID => 'Belum Lunas',
        self::ACCOUNT_PAYABLE_STATUS_ONGOING => 'Proses',
        self::ACCOUNT_PAYABLE_STATUS_PAID => 'Lunas',
    ];

    const ACCOUNT_PAYABLE_STATUSES = [
        self::ACCOUNT_RECEIVABLE_STATUS_UNPAID,
        self::ACCOUNT_RECEIVABLE_STATUS_ONGOING,
        self::ACCOUNT_RECEIVABLE_STATUS_PAID
    ];

    const ACCOUNT_RECEIVABLE_STATUS_UNPAID = 'UNPAID';
    const ACCOUNT_RECEIVABLE_STATUS_ONGOING = 'ONGOING';
    const ACCOUNT_RECEIVABLE_STATUS_PAID = 'PAID';
    const ACCOUNT_RECEIVABLE_STATUS_LABELS = [
        self::ACCOUNT_RECEIVABLE_STATUS_UNPAID => 'Belum Lunas',
        self::ACCOUNT_RECEIVABLE_STATUS_ONGOING => 'Proses',
        self::ACCOUNT_RECEIVABLE_STATUS_PAID => 'Lunas',
    ];

    const ACCOUNT_RECEIVABLE_STATUSES = [
        self::ACCOUNT_RECEIVABLE_STATUS_UNPAID,
        self::ACCOUNT_RECEIVABLE_STATUS_ONGOING,
        self::ACCOUNT_RECEIVABLE_STATUS_PAID
    ];

    const APPROVAL_SUBJECT_TYPE_SALES_ORDER = 'SALES_ORDER';
    const APPROVAL_SUBJECT_TYPE_GOODS_RECEIPT = 'GOODS_RECEIPT';
    const APPROVAL_SUBJECT_TYPE_DELIVERY_ORDER = 'DELIVERY_ORDER';
    const APPROVAL_SUBJECT_TYPE_SALES_RETURN = 'SALES_RETURN';
    const APPROVAL_SUBJECT_TYPE_PURCHASE_RETURN = 'PURCHASE_RETURN';

    const APPROVAL_SUBJECT_TYPE_LABELS = [
        self::APPROVAL_SUBJECT_TYPE_SALES_ORDER => 'Sales Order',
        self::APPROVAL_SUBJECT_TYPE_GOODS_RECEIPT => 'Barang Masuk',
        self::APPROVAL_SUBJECT_TYPE_DELIVERY_ORDER => 'Surat Jalan',
        self::APPROVAL_SUBJECT_TYPE_SALES_RETURN => 'Retur Penjualan',
        self::APPROVAL_SUBJECT_TYPE_PURCHASE_RETURN => 'Retur Pembelian',
    ];

    const APPROVAL_TYPE_EDIT = 'EDIT';
    const APPROVAL_TYPE_CANCEL = 'CANCEL';
    const APPROVAL_TYPE_APPROVAL_LIMIT = 'APPROVAL_LIMIT';
    const APPROVAL_TYPE_LABELS = [
        self::APPROVAL_TYPE_EDIT => 'Ubah',
        self::APPROVAL_TYPE_CANCEL => 'Batal',
        self::APPROVAL_TYPE_APPROVAL_LIMIT => 'Approval Limit',
    ];

    const APPROVAL_STATUS_PENDING = 'PENDING';
    const APPROVAL_STATUS_APPROVED = 'APPROVED';
    const APPROVAL_STATUS_REJECTED = 'REJECTED';
    const APPROVAL_STATUS_LABELS = [
        self::APPROVAL_STATUS_PENDING => 'Pending',
        self::APPROVAL_STATUS_APPROVED => 'Disetujui',
        self::APPROVAL_STATUS_REJECTED => 'Ditolak',
    ];

    const PRODUCT_STOCK_LOG_TYPE_GOODS_RECEIPT = 'GOODS_RECEIPT';
    const PRODUCT_STOCK_LOG_TYPE_SALES_ORDER = 'SALES_ORDER';
    const PRODUCT_STOCK_LOG_TYPE_PURCHASE_RETURN = 'PURCHASE_RETURN';
    const PRODUCT_STOCK_LOG_TYPE_SALES_RETURN = 'SALES_RETURN';
    const PRODUCT_STOCK_LOG_TYPE_MANUAL_EDIT = 'MANUAL_EDIT';
    const PRODUCT_STOCK_LOG_TYPE_LABELS = [
        self::PRODUCT_STOCK_LOG_TYPE_GOODS_RECEIPT => 'Barang Masuk',
        self::PRODUCT_STOCK_LOG_TYPE_SALES_ORDER => 'Sales Order',
        self::PRODUCT_STOCK_LOG_TYPE_PURCHASE_RETURN => 'Retur Pembelian',
        self::PRODUCT_STOCK_LOG_TYPE_SALES_RETURN => 'Retur Penjualan',
        self::PRODUCT_STOCK_LOG_TYPE_MANUAL_EDIT => 'Ubah Manual',
    ];

    const PRODUCT_STOCK_LOG_TYPE_ROUTE = [
        self::PRODUCT_STOCK_LOG_TYPE_GOODS_RECEIPT => 'goods-receipts',
        self::PRODUCT_STOCK_LOG_TYPE_SALES_ORDER => 'sales-orders',
        self::PRODUCT_STOCK_LOG_TYPE_PURCHASE_RETURN => 'purchase-returns',
        self::PRODUCT_STOCK_LOG_TYPE_SALES_RETURN => 'sales-returns',
        self::PRODUCT_STOCK_LOG_TYPE_MANUAL_EDIT => 'products',
    ];

    const NUMBER_SETTING_KEY_PLAN_ORDER = 'PO';
    const NUMBER_SETTING_KEY_GOODS_RECEIPT = 'GR';
    const NUMBER_SETTING_KEY_SALES_ORDER = 'SO';
    const NUMBER_SETTING_KEY_DELIVERY_ORDER = 'DO';
    const NUMBER_SETTING_KEY_SALES_RETURN = 'SR';
    const NUMBER_SETTING_KEY_PURCHASE_RETURN = 'PR';

    const SALES_RECAP_TYPE_PRODUCT = 'product';
    const SALES_RECAP_TYPE_CUSTOMER = 'customer';
    const SALES_RECAP_TYPE_LABELS = [
        self::SALES_RECAP_TYPE_PRODUCT => 'Produk',
        self::SALES_RECAP_TYPE_CUSTOMER => 'Customer',
    ];

    const PURCHASE_RECAP_TYPE_PRODUCT = 'product';
    const PURCHASE_RECAP_TYPE_SUPPLIER = 'supplier';
    const PURCHASE_RECAP_TYPE_LABELS = [
        self::PURCHASE_RECAP_TYPE_PRODUCT => 'Produk',
        self::PURCHASE_RECAP_TYPE_SUPPLIER => 'Supplier',
    ];
}
