<?php

namespace App\Utilities;

class Constant
{
    const USER_ROLE_SUPER_ADMIN = 'SUPER_ADMIN';
    const USER_ROLE_ADMIN = 'ADMIN';
    const USER_ROLE_FINANCE = 'FINANCE';
    const USER_ROLE_WAREHOUSE = 'WAREHOUSE';
    const USER_ROLES = [
        self::USER_ROLE_SUPER_ADMIN,
        self::USER_ROLE_ADMIN,
        self::USER_ROLE_FINANCE,
        self::USER_ROLE_WAREHOUSE,
    ];
    const USER_ROLE_LABELS = [
        self::USER_ROLE_SUPER_ADMIN => 'Super Admin',
        self::USER_ROLE_ADMIN => 'Admin',
        self::USER_ROLE_FINANCE => 'Finance',
        self::USER_ROLE_WAREHOUSE => 'Warehouse',
    ];

    const USER_STATUS_PENDING = 'PENDING';
    const USER_STATUS_ACTIVE = 'ACTIVE';
    const USER_STATUS_LABELS = [
        self::USER_STATUS_PENDING => 'Pending',
        self::USER_STATUS_ACTIVE => 'Active'
    ];

    const WAREHOUSE_TYPE_PRIMARY = 'PRIMARY';
    const WAREHOUSE_TYPE_SECONDARY = 'SECONDARY';
    const WAREHOUSE_TYPE_RETURN = 'RETURN';

    const WAREHOUSE_TYPES = [
        self::WAREHOUSE_TYPE_PRIMARY,
        self::WAREHOUSE_TYPE_SECONDARY,
        self::WAREHOUSE_TYPE_RETURN,
    ];
    const WAREHOUSE_TYPE_LABELS = [
        self::WAREHOUSE_TYPE_PRIMARY => 'Primary',
        self::WAREHOUSE_TYPE_SECONDARY => 'Secondary',
        self::WAREHOUSE_TYPE_RETURN => 'Return'
    ];

    const PRICE_TYPE_GENERAL = 'GENERAL';
    const PRICE_TYPE_RETAIL = 'RETAIL';
    const PRICE_TYPE_WHOLESALE = 'WHOLESALE';
    const PRICE_TYPES = [
        self::PRICE_TYPE_GENERAL,
        self::PRICE_TYPE_RETAIL,
        self::PRICE_TYPE_WHOLESALE,
    ];
    const PRICE_TYPE_LABELS = [
        self::PRICE_TYPE_GENERAL => 'General',
        self::PRICE_TYPE_RETAIL => 'Retail',
        self::PRICE_TYPE_WHOLESALE => 'Wholesale'
    ];

    const GOODS_RECEIPT_STATUS_ACTIVE = 'ACTIVE';
    const GOODS_RECEIPT_STATUS_WAITING_APPROVAL = 'WAITING_APPROVAL';
    const GOODS_RECEIPT_STATUS_UPDATED = 'UPDATED';
    const GOODS_RECEIPT_STATUS_CANCELLED = 'CANCELLED';
    const GOODS_RECEIPT_STATUS_LABELS = [
        self::GOODS_RECEIPT_STATUS_ACTIVE => 'Active',
        self::GOODS_RECEIPT_STATUS_WAITING_APPROVAL => 'Waiting Approval',
        self::GOODS_RECEIPT_STATUS_UPDATED => 'Updated',
        self::GOODS_RECEIPT_STATUS_CANCELLED => 'Cancelled',
    ];

    const PRODUCT_TRANSFER_STATUS_ACTIVE = 'ACTIVE';
    const PRODUCT_TRANSFER_STATUS_WAITING_APPROVAL = 'WAITING_APPROVAL';
    const PRODUCT_TRANSFER_STATUS_CANCELLED = 'CANCELLED';
    const PRODUCT_TRANSFER_STATUS_LABELS = [
        self::PRODUCT_TRANSFER_STATUS_ACTIVE => 'Active',
        self::PRODUCT_TRANSFER_STATUS_WAITING_APPROVAL => 'Waiting Approval',
        self::PRODUCT_TRANSFER_STATUS_CANCELLED => 'Cancelled',
    ];

    const SALES_ORDER_STATUS_ACTIVE = 'ACTIVE';
    const SALES_ORDER_STATUS_WAITING_APPROVAL = 'WAITING_APPROVAL';
    const SALES_ORDER_STATUS_UPDATED = 'UPDATED';
    const SALES_ORDER_STATUS_CANCELLED = 'CANCELLED';
    const SALES_ORDER_STATUS_LABELS = [
        self::SALES_ORDER_STATUS_ACTIVE => 'Active',
        self::SALES_ORDER_STATUS_WAITING_APPROVAL => 'Waiting Approval',
        self::SALES_ORDER_STATUS_UPDATED => 'Updated',
        self::SALES_ORDER_STATUS_CANCELLED => 'Cancelled',
    ];

    const SALES_ORDER_DELIVERY_STATUS_ACTIVE = 'ACTIVE';
    const SALES_ORDER_DELIVERY_STATUS_ON_PROGRESS = 'ON_PROGRESS';
    const SALES_ORDER_DELIVERY_STATUS_COMPLETED = 'COMPLETED';
    const SALES_ORDER_DELIVERY_STATUS_LABELS = [
        self::SALES_ORDER_DELIVERY_STATUS_ACTIVE => 'Active',
        self::SALES_ORDER_DELIVERY_STATUS_ON_PROGRESS => 'On Progress',
        self::SALES_ORDER_DELIVERY_STATUS_COMPLETED => 'Completed',
    ];

    const SALES_ORDER_TYPE_RETAIL = 'RETAIL';
    const SALES_ORDER_TYPE_WHOLESALE = 'WHOLESALE';
    const SALES_ORDER_TYPE_LABELS = [
        self::SALES_ORDER_TYPE_RETAIL => 'Retail',
        self::SALES_ORDER_TYPE_WHOLESALE => 'Wholesale',
    ];

    const DELIVERY_ORDER_STATUS_ACTIVE = 'ACTIVE';
    const DELIVERY_ORDER_STATUS_WAITING_APPROVAL = 'WAITING_APPROVAL';
    const DELIVERY_ORDER_STATUS_UPDATED = 'UPDATED';
    const DELIVERY_ORDER_STATUS_CANCELLED = 'CANCELLED';
    const DELIVERY_ORDER_STATUS_LABELS = [
        self::DELIVERY_ORDER_STATUS_ACTIVE => 'Active',
        self::DELIVERY_ORDER_STATUS_WAITING_APPROVAL => 'Waiting Approval',
        self::DELIVERY_ORDER_STATUS_UPDATED => 'Updated',
        self::DELIVERY_ORDER_STATUS_CANCELLED => 'Cancelled',
    ];

    const ACCOUNT_PAYABLE_STATUS_UNPAID = 'UNPAID';
    const ACCOUNT_PAYABLE_STATUS_ONGOING = 'ONGOING';
    const ACCOUNT_PAYABLE_STATUS_PAID = 'PAID';
    const ACCOUNT_PAYABLE_STATUS_LABELS = [
        self::ACCOUNT_PAYABLE_STATUS_UNPAID => 'Unpaid',
        self::ACCOUNT_PAYABLE_STATUS_ONGOING => 'Ongoing',
        self::ACCOUNT_PAYABLE_STATUS_PAID => 'Paid',
    ];

    const ACCOUNT_PAYABLE_STATUSES = [
        self::ACCOUNT_RECEIVABLE_STATUS_UNPAID,
        self::ACCOUNT_RECEIVABLE_STATUS_ONGOING,
        self::ACCOUNT_RECEIVABLE_STATUS_PAID
    ];

    const ACCOUNT_RECEIVABLE_STATUS_UNPAID = 'UNPAID';
    const ACCOUNT_RECEIVABLE_STATUS_ONGOING = 'ONGOING';
    const ACCOUNT_RECEIVABLE_STATUS_PAID = 'PAID';
    const ACCOUNT_RECEIVABLE_STATUS_LABELS = [
        self::ACCOUNT_RECEIVABLE_STATUS_UNPAID => 'Unpaid',
        self::ACCOUNT_RECEIVABLE_STATUS_ONGOING => 'Ongoing',
        self::ACCOUNT_RECEIVABLE_STATUS_PAID => 'Paid',
    ];

    const ACCOUNT_RECEIVABLE_STATUSES = [
        self::ACCOUNT_RECEIVABLE_STATUS_UNPAID,
        self::ACCOUNT_RECEIVABLE_STATUS_ONGOING,
        self::ACCOUNT_RECEIVABLE_STATUS_PAID
    ];

    const APPROVAL_SUBJECT_TYPE_SALES_ORDER = 'SALES_ORDER';
    const APPROVAL_SUBJECT_TYPE_GOODS_RECEIPT = 'GOODS_RECEIPT';
    const APPROVAL_SUBJECT_TYPE_PRODUCT_TRANSFER = 'PRODUCT_TRANSFER';
    const APPROVAL_SUBJECT_TYPE_DELIVERY_ORDER = 'DELIVERY_ORDER';

    const APPROVAL_SUBJECT_TYPE_LABELS = [
        self::APPROVAL_SUBJECT_TYPE_SALES_ORDER => 'Sales Order',
        self::APPROVAL_SUBJECT_TYPE_GOODS_RECEIPT => 'Goods Receipt',
        self::APPROVAL_SUBJECT_TYPE_PRODUCT_TRANSFER => 'Product Transfer',
        self::APPROVAL_SUBJECT_TYPE_DELIVERY_ORDER => 'Delivery Order',
    ];

    const APPROVAL_TYPE_EDIT = 'EDIT';
    const APPROVAL_TYPE_CANCEL = 'CANCEL';
    const APPROVAL_TYPE_APPROVAL_LIMIT = 'APPROVAL_LIMIT';
    const APPROVAL_TYPE_LABELS = [
        self::APPROVAL_TYPE_EDIT => 'Edit',
        self::APPROVAL_TYPE_CANCEL => 'Cancel',
        self::APPROVAL_TYPE_APPROVAL_LIMIT => 'Approval Limit',
    ];

    const APPROVAL_STATUS_PENDING = 'PENDING';
    const APPROVAL_STATUS_APPROVED = 'APPROVED';
    const APPROVAL_STATUS_REJECTED = 'REJECTED';
    const APPROVAL_STATUS_LABELS = [
        self::APPROVAL_STATUS_PENDING => 'Pending',
        self::APPROVAL_STATUS_APPROVED => 'Approved',
        self::APPROVAL_STATUS_REJECTED => 'Rejected',
    ];


}
